### ISSUE TITLE
[Doctolib] Mauvais parse lorsque le pid est un etablissement

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#170]
```
Error: m2021-04-13 10:51:10,133 | [ERROR] erreur lors du traitement de la ligne avec le gid 1448
Traceback (most recent call last):
  File "/home/runner/work/vitemadose/vitemadose/scraper/scraper.py", line 92, in cherche_prochain_rdv_dans_centre
    result = fetch_centre_slots(centre['rdv_site_web'], start_date)
  File "/home/runner/work/vitemadose/vitemadose/scraper/scraper.py", line 232, in fetch_centre_slots
    result.next_availability = fetch_impl(request)
  File "/home/runner/work/vitemadose/vitemadose/scraper/doctolib/doctolib.py", line 41, in fetch_slots
    return doctolib.fetch(request)
  File "/home/runner/work/vitemadose/vitemadose/scraper/doctolib/doctolib.py", line 73, in fetch
    practice_id = link_practice_ids(practice_id, rdata)
  File "/home/runner/work/vitemadose/vitemadose/scraper/doctolib/doctolib.py", line 185, in link_practice_ids
    place_ids.append(int(place_id.replace("practice-", "")))
ValueError: invalid literal for int() with base 10: 'establishment-7149'
```

**Comment by Noezor** [comment]
Code snippet lié : is_practice_id_valid

**Comment by grubounet** [comment]
J'ai profité de la #267 pour essayer de corriger ça
