### ISSUE TITLE
Exception non géré dans le scrapper

### ISSUE THREAD

**Issue by Olivier4477** [CovidTrackerFr/vitemadose#356]
```
2021-05-08 07:11:00,623 | [INFO]  d242168 Doctolib                                          45    
2021-05-08 07:11:00,695 | [ERROR] erreur lors du traitement de la ligne avec le gid d243144
Traceback (most recent call last):
  File "/builds/ViteMaDose/vitemadose/scraper/scraper.py", line 100, in cherche_prochain_rdv_dans_centre
    result = fetch_centre_slots(centre["rdv_site_web"], start_date)
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 69, in with_profiling
    raise error
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 61, in with_profiling
    ret = fn(*args, **kwargs)
  File "/builds/ViteMaDose/vitemadose/scraper/scraper.py", line 270, in fetch_centre_slots
    result.next_availability = fetch_impl(request)
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 69, in with_profiling
    raise error
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 61, in with_profiling
    ret = fn(*args, **kwargs)
  File "/builds/ViteMaDose/vitemadose/scraper/doctolib/doctolib.py", line 44, in fetch_slots
    return doctolib.fetch(request)
  File "/builds/ViteMaDose/vitemadose/scraper/doctolib/doctolib.py", line 116, in fetch
    sdate, appt, count_next_appt, stop = self.get_appointments(
  File "/builds/ViteMaDose/vitemadose/scraper/doctolib/doctolib.py", line 212, in get_appointments
    response.raise_for_status()
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_models.py", line 1105, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: 400 Client Error: Bad Request for url: https://partners.doctolib.fr/availabilities.json?start_date=2021-05-08&visit_motive_ids=2851776&agenda_ids=472962-472951-472948-472949-472950-472952-472953&insurance_sector=public&practice_ids=164775&destroy_temporary=true&limit=7
For more information check: https://httpstatuses.com/400
```

**Comment by Olivier4477** [comment]
2021-05-11 06:53:05,596 | [ERROR] erreur lors du traitement de la ligne avec le gid d242644
Traceback (most recent call last):
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 856, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_transports/default.py", line 102, in request
    return self._pool.request(method, url, headers=headers, stream=stream, ext=ext)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 218, in request
    response = connection.request(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 106, in request
    return self.connection.request(method, url, headers, stream, ext)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 72, in request
    ) = self._receive_response(timeout)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 133, in _receive_response
    event = self._receive_event(timeout)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 172, in _receive_event
    data = self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_backends/sync.py", line 62, in read
    return self.sock.recv(n)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ReadTimeout: The read operation timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/builds/ViteMaDose/vitemadose/scraper/scraper.py", line 89, in cherche_prochain_rdv_dans_centre
    result = fetch_centre_slots(centre["rdv_site_web"], start_date)
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 69, in with_profiling
    raise error
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 61, in with_profiling
    ret = fn(*args, **kwargs)
  File "/builds/ViteMaDose/vitemadose/scraper/scraper.py", line 178, in fetch_centre_slots
    result.next_availability = fetch_impl(request)
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 69, in with_profiling
    raise error
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 61, in with_profiling
    ret = fn(*args, **kwargs)
  File "/builds/ViteMaDose/vitemadose/scraper/doctolib/doctolib.py", line 56, in fetch_slots
    return doctolib.fetch(request)
  File "/builds/ViteMaDose/vitemadose/scraper/doctolib/doctolib.py", line 148, in fetch
    sdate, appt, appointment_schedules, stop = self.get_appointments(
  File "/builds/ViteMaDose/vitemadose/scraper/doctolib/doctolib.py", line 234, in get_appointments
    response = self._client.get(slots_api_url, headers=DOCTOLIB_HEADERS)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 902, in get
    return self.request(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 728, in request
    return self.send(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 762, in send
    response = self._send_handling_auth(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 800, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 832, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 856, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ReadTimeout: The read operation timed out

**Comment by Olivier4477** [comment]
scrapper du 11/05 Runner: #5585616 (mdofwECw) Chez OVH SBG5 (num 0)
2021-05-11 06:52:47,090 | [ERROR] erreur lors du traitement de la ligne avec le gid d269908
Traceback (most recent call last):
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 856, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_transports/default.py", line 102, in request
    return self._pool.request(method, url, headers=headers, stream=stream, ext=ext)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 218, in request
    response = connection.request(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 106, in request
    return self.connection.request(method, url, headers, stream, ext)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 72, in request
    ) = self._receive_response(timeout)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 133, in _receive_response
    event = self._receive_event(timeout)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_sync/http11.py", line 172, in _receive_event
    data = self.socket.read(self.READ_NUM_BYTES, timeout)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_backends/sync.py", line 62, in read
    return self.sock.recv(n)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ReadTimeout: The read operation timed out
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/builds/ViteMaDose/vitemadose/scraper/scraper.py", line 89, in cherche_prochain_rdv_dans_centre
    result = fetch_centre_slots(centre["rdv_site_web"], start_date)
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 69, in with_profiling
    raise error
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 61, in with_profiling
    ret = fn(*args, **kwargs)
  File "/builds/ViteMaDose/vitemadose/scraper/scraper.py", line 178, in fetch_centre_slots
    result.next_availability = fetch_impl(request)
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 69, in with_profiling
    raise error
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 61, in with_profiling
    ret = fn(*args, **kwargs)
  File "/builds/ViteMaDose/vitemadose/scraper/doctolib/doctolib.py", line 56, in fetch_slots
    return doctolib.fetch(request)
  File "/builds/ViteMaDose/vitemadose/scraper/doctolib/doctolib.py", line 148, in fetch
    sdate, appt, appointment_schedules, stop = self.get_appointments(
  File "/builds/ViteMaDose/vitemadose/scraper/doctolib/doctolib.py", line 234, in get_appointments
    response = self._client.get(slots_api_url, headers=DOCTOLIB_HEADERS)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 902, in get
    return self.request(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 728, in request
    return self.send(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 762, in send
    response = self._send_handling_auth(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 800, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 832, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 856, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ReadTimeout: The read operation timed out

**Comment by Olivier4477** [comment]
runner du 11/05 5585616 (mdofwECw) Chez OVH SBG5 (num 0)
```

2021-05-11 11:09:13,407 | [ERROR] erreur lors du traitement de la ligne avec le gid 1045
2021-05-11 11:09:13,410 | [INFO]  d242556 Doctolib         2021-05-17T13:15:00.000+02:00    03    
Traceback (most recent call last):
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_exceptions.py", line 326, in map_exceptions
    yield
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 856, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_transports/default.py", line 102, in request
    return self._pool.request(method, url, headers=headers, stream=stream, ext=ext)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 218, in request
    response = connection.request(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 93, in request
    self.socket = self._open_socket(timeout)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 119, in _open_socket
    return self.backend.open_tcp_stream(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_backends/sync.py", line 143, in open_tcp_stream
    return SyncSocketStream(sock=sock)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc) from None
httpcore.ConnectError: EOF occurred in violation of protocol (_ssl.c:1131)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/builds/ViteMaDose/vitemadose/scraper/scraper.py", line 89, in cherche_prochain_rdv_dans_centre
    result = fetch_centre_slots(centre["rdv_site_web"], start_date)
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 69, in with_profiling
    raise error
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 61, in with_profiling
    ret = fn(*args, **kwargs)
  File "/builds/ViteMaDose/vitemadose/scraper/scraper.py", line 178, in fetch_centre_slots
    result.next_availability = fetch_impl(request)
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 69, in with_profiling
    raise error
  File "/builds/ViteMaDose/vitemadose/scraper/profiler.py", line 61, in with_profiling
    ret = fn(*args, **kwargs)
  File "/builds/ViteMaDose/vitemadose/scraper/keldoc/keldoc.py", line 34, in fetch_slots
    if not center.fetch_center_data():
  File "/builds/ViteMaDose/vitemadose/scraper/keldoc/keldoc_center.py", line 65, in fetch_center_data
    resource = self.client.get(API_KELDOC_CENTER, params=self.resource_params)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 902, in get
    return self.request(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 728, in request
    return self.send(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 762, in send
    response = self._send_handling_auth(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 800, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 832, in _send_handling_redirects
    response = self._send_single_request(request, timeout)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_client.py", line 856, in _send_single_request
    (status_code, headers, stream, ext) = transport.request(
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/builds/ViteMaDose/vitemadose/venv/lib/python3.8/site-packages/httpx/_exceptions.py", line 343, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectError: EOF occurred in violation of protocol (_ssl.c:1131)
2021-05-11 11:09:13,411 | [INFO]     1045 None                                              59    
```
