### ISSUE TITLE
Impossible de scrap Keldoc

### ISSUE THREAD

**Issue by aureliancnx** [CovidTrackerFr/vitemadose#586]
Sur certains départements, il est impossible de run le scraper de centres pour Keldoc à cause de valeurs qui ont été modifiées

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.10/x64/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/runner/work/vitemadose/vitemadose/scraper/keldoc/keldoc_center_scrap.py", line 127, in fetch_department
    return scraper.run_departement_scrap(department)
  File "/home/runner/work/vitemadose/vitemadose/scraper/keldoc/keldoc_center_scrap.py", line 32, in run_departement_scrap
    centers_departements = self.parse_pages_departement(departement)
  File "/home/runner/work/vitemadose/vitemadose/scraper/keldoc/keldoc_center_scrap.py", line 111, in parse_pages_departement
    parsed_center = self.parse_keldoc_center(center_data)
  File "/home/runner/work/vitemadose/vitemadose/scraper/keldoc/keldoc_center_scrap.py", line 76, in parse_keldoc_center
    data["resources"] = self.parse_keldoc_resources(center)
  File "/home/runner/work/vitemadose/vitemadose/scraper/keldoc/keldoc_center_scrap.py", line 53, in parse_keldoc_resources
    resource_url = parse_keldoc_resource_url(center)
  File "/home/runner/work/vitemadose/vitemadose/scraper/keldoc/keldoc_center_scrap.py", line 153, in parse_keldoc_resource_url
    type, location, slug = url_split[1:4]
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by aureliancnx** [comment]
Fixé par https://github.com/CovidTrackerFr/vitemadose/commit/0b77c8453751fdf3d81c16c6736691196a377768 et https://github.com/CovidTrackerFr/vitemadose/commit/916f6f6c00685ce7436b83c56c0d2d6f574bd331
